### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by Balikuddembe** [Balikuddembe/Space-Travelers-Hub#25]
https://github.com/Balikuddembe/Space-Travelers-Hub/projects/1

Hello 👋 ,
We are two people working on this project;
@ivanmvh and
@Balikuddembe

**Comment by topeogunleye** [comment]
Hi Team, 

Your project is complete! Congratulations! 🥂There is nothing else to say other than... it's time to merge it 👍.

- All linters are passing :heavy_check_mark: 

## Optional suggestions
_Please keep in mind that you, for best practices and following the project requirements and the design templates closely 

- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
